server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springexample
      username: root
      password: example
      authentication-database: admin
